# Generated by Django 4.0.4 on 2022-05-06 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_articulo', models.CharField(help_text='Nombre del artículo', max_length=50, verbose_name='Nombre del Artículo')),
                ('precio', models.FloatField(help_text='Precio del artículo', verbose_name='Precio del Artículo')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cliente', models.CharField(help_text='Nombre del cliente', max_length=50, verbose_name='Nombre Cliente')),
                ('estado', models.CharField(help_text='Estado', max_length=50, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Cliente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de la orden', verbose_name='Fecha de la Orden')),
                ('cliente', models.ForeignKey(help_text='Cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='alm.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Orden',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArticuloOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.PositiveIntegerField(default=0, help_text='Cantidad del artículo', verbose_name='Cantidad del Artículo')),
                ('articulo', models.ForeignKey(help_text='Artículo', on_delete=django.db.models.deletion.DO_NOTHING, to='alm.articulo', verbose_name='Artículo')),
                ('orden', models.ForeignKey(help_text='Orden', on_delete=django.db.models.deletion.DO_NOTHING, to='alm.orden', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Artículo Orden',
                'verbose_name_plural': 'Artículo Orden',
                'ordering': ['id'],
                'unique_together': {('articulo', 'orden')},
            },
        ),
    ]
