# Generated by Django 4.0.4 on 2025-10-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm', '0003_alter_venta_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo_movimiento',
            field=models.CharField(
                choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')],
                default='INGRESO',
                max_length=10
            ),
        ),
    ]
