# Generated by Django - Migración de datos

from django.db import migrations


def actualizar_codigos_productos(apps, schema_editor):
    """
    Actualiza los códigos de todos los productos existentes
    según el formato: PREFIJO-001, PREFIJO-002, etc.
    donde PREFIJO son las primeras 3 letras de la categoría
    """
    Producto = apps.get_model('alm', 'Producto')
    Categoria = apps.get_model('alm', 'Categoria')

    # Obtener todas las categorías
    categorias = Categoria.objects.all()

    for categoria in categorias:
        # Prefijo de 3 letras de la categoría
        prefijo = categoria.nombre[:3].upper()

        # Obtener todos los productos de esta categoría (incluyendo eliminados)
        productos = Producto.objects.filter(categoria=categoria).order_by('id')

        # Asignar códigos correlativos
        for index, producto in enumerate(productos, start=1):
            nuevo_codigo = f"{prefijo}-{index:03d}"
            producto.codigo = nuevo_codigo
            producto.save()
            print(f"Producto actualizado: {producto.nombre} -> {nuevo_codigo}")


def revertir_actualizacion(apps, schema_editor):
    """
    Función de reversión (opcional, no hace nada porque los códigos antiguos se pierden)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('alm', '0006_alter_producto_codigo'),
    ]

    operations = [
        migrations.RunPython(actualizar_codigos_productos, revertir_actualizacion),
    ]
