# Generated by Django 4.2.7 on 2025-10-20
# Migration to allow blank codigo_variante for auto-generation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm', '0009_actualizar_datos_abonos_ventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productovariante',
            name='codigo_variante',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
