# Generated by Django 4.0.4 on 2025-10-23 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alm', '0010_alter_productovariante_codigo_variante'),
    ]

    operations = [
        migrations.AddField(
            model_name='productovariante',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.CreateModel(
            name='PromocionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la promoción (solo para referencia interna)', max_length=200)),
                ('mensaje', models.TextField(help_text='Mensaje que se enviará. Usa {nombre} para personalizar')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIANDO', 'Enviando'), ('ENVIADO', 'Enviado'), ('ERROR', 'Error')], default='BORRADOR', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, help_text='Fecha y hora en que se envió la promoción', null=True)),
                ('total_destinatarios', models.IntegerField(default=0)),
                ('mensajes_enviados', models.IntegerField(default=0)),
                ('mensajes_fallidos', models.IntegerField(default=0)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promoción WhatsApp',
                'verbose_name_plural': 'Promociones WhatsApp',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EnvioWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15)),
                ('mensaje_enviado', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=10)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('sid_twilio', models.CharField(blank=True, help_text='ID del mensaje en Twilio', max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alm.cliente')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='alm.promocionwhatsapp')),
            ],
            options={
                'verbose_name': 'Envío WhatsApp',
                'verbose_name_plural': 'Envíos WhatsApp',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
