[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[start]
cmd = "cd backend/almacen && python manage.py add_tipo_movimiento && python manage.py migrate --noinput && python manage.py create_superuser && python manage.py collectstatic --noinput && gunicorn almacen.wsgi:application --bind 0.0.0.0:${PORT:-8000} --workers 2 --timeout 120"
